version: "3.9"
services:

  ocrd-controller:
    build:
      context: .
      # args:
      #   VCS_REF: ...
      #   BUILD_DATE: ...

    image: ${CONTROLLER_IMAGE}

    hostname: ${CONTROLLER_HOST}

    environment:
      - UID=${CONTROLLER_ENV_UID}
      - GID=${CONTROLLER_ENV_GID}
      - UMASK=${CONTROLLER_ENV_UMASK}
      - WORKERS=${CONTROLLER_WORKERS}

    ports:
      - ${CONTROLLER_PORT_SSH}:22

    volumes:
      - type: bind
        source: ${CONTROLLER_KEYS} # ocrd manager public key
        target: /authorized_keys
      - ${CONTROLLER_MODELS}:/models # Resource directory
      - ${CONTROLLER_CONFIG}:/config
      - ${CONTROLLER_DATA}:/data

    deploy:
      resources:
        limits:
          cpus: ${CONTROLLER_WORKERS}
        reservations:
          devices:
            - capabilities: [gpu]
